version: "3.4"

services:
  postgres:
    container_name: "threads_DB"
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data: